/*
 * CaDS Zero - embedded artwork.
 *
 * Images are 4 bpp indexed against the canvas palette (gui/canvas.h), which
 * means the CaDS mark's three brand colours land on palette slots 2, 3 and 4
 * exactly rather than approximately. Generated by scripts/gen_asset.py.
 */

#ifndef CADS_ASSETS_H
#define CADS_ASSETS_H

#include <stdint.h>

typedef struct {
    uint16_t width;
    uint16_t height;
    uint8_t transparent; /**< palette index treated as see-through */
    const uint8_t* data; /**< 4 bpp, high nibble first, rows byte aligned */
} cads_image_t;

/** The full CaDS mark: wordmark, lion and tagline. */
extern const cads_image_t cads_logo;

/** Leo, the lion. Mascot, and the desktop's resident opinion-haver. */
extern const cads_image_t cads_leo;

#endif /* CADS_ASSETS_H */
