/* modules/security's AEAD wrapper - see cads/security/secure_link.h for the
 * design rationale (fixed PSK, no forward secrecy, caller-supplied nonce).
 *
 * test_known_vector_matches_libsodium is the one that actually matters most:
 * it is not a self-referential round-trip (which would pass even if this
 * wrapper's nonce/key/AD wiring were subtly wrong, as long as it were wrong
 * the same way on both seal and open) - it is a real cross-implementation
 * vector generated by an independent reference (PyNaCl/libsodium's
 * crypto_aead_xchacha20poly1305_ietf, the same construction Monocypher's
 * crypto_aead_lock documents itself as compatible with), so it actually
 * catches a construction mismatch (wrong nonce size interpretation, wrong
 * byte order, AD handled differently) that a pure round-trip test cannot.
 * This is what a Mac-side Python implementation talking to this same board
 * would need to interoperate with. */

#include <string.h>

#include "unity.h"

#include "cads/security/secure_link.h"

void setUp(void) {
}

void tearDown(void) {
}

/* Generated 2026-08-28 via PyNaCl (libsodium) crypto_aead_xchacha20poly1305_
 * ietf_encrypt with a fixed, non-secret key/nonce/ad/plaintext - see this
 * repo's commit message for the exact generation script. Never reuse this
 * key/nonce pair for anything real; it exists only to pin this wrapper's
 * wire format against an independent implementation. */
static const uint8_t s_key[CADS_SECURE_LINK_KEY_LEN] = {
    0x00u, 0x01u, 0x02u, 0x03u, 0x04u, 0x05u, 0x06u, 0x07u, 0x08u, 0x09u, 0x0au, 0x0bu,
    0x0cu, 0x0du, 0x0eu, 0x0fu, 0x10u, 0x11u, 0x12u, 0x13u, 0x14u, 0x15u, 0x16u, 0x17u,
    0x18u, 0x19u, 0x1au, 0x1bu, 0x1cu, 0x1du, 0x1eu, 0x1fu};
static const uint8_t s_nonce[CADS_SECURE_LINK_NONCE_LEN] = {
    0x00u, 0x01u, 0x02u, 0x03u, 0x04u, 0x05u, 0x06u, 0x07u, 0x08u, 0x09u, 0x0au, 0x0bu,
    0x0cu, 0x0du, 0x0eu, 0x0fu, 0x10u, 0x11u, 0x12u, 0x13u, 0x14u, 0x15u, 0x16u, 0x17u};
static const uint8_t s_ad[12] = {
    0x43u, 0x61u, 0x44u, 0x53u, 0x20u, 0x5au, 0x65u, 0x72u, 0x6fu, 0x20u, 0x41u, 0x44u};
static const uint8_t s_plain[27] = {
    0x48u, 0x65u, 0x6cu, 0x6cu, 0x6fu, 0x20u, 0x66u, 0x72u, 0x6fu, 0x6du, 0x20u, 0x74u,
    0x68u, 0x65u, 0x20u, 0x53u, 0x54u, 0x4du, 0x33u, 0x32u, 0x20u, 0x62u, 0x6fu, 0x61u,
    0x72u, 0x64u, 0x21u};
static const uint8_t s_expected_cipher[27] = {
    0xd6u, 0xa7u, 0x63u, 0x13u, 0xffu, 0xf2u, 0xebu, 0xdcu, 0x5cu, 0x29u, 0x06u, 0xbau,
    0xa3u, 0x37u, 0x88u, 0xbbu, 0x1fu, 0x0au, 0x1bu, 0x97u, 0xddu, 0xb4u, 0x72u, 0x8au,
    0x0du, 0x7eu, 0x1eu};
static const uint8_t s_expected_mac[CADS_SECURE_LINK_MAC_LEN] = {
    0x1du, 0x8fu, 0x67u, 0xe5u, 0xb0u, 0xfcu, 0xf9u, 0x3au, 0x2eu, 0x6cu, 0x5au, 0xf1u,
    0x5au, 0xafu, 0xb1u, 0x2cu};

static void test_known_vector_matches_libsodium(void) {
    uint8_t cipher[sizeof(s_plain)];
    uint8_t mac[CADS_SECURE_LINK_MAC_LEN];
    cads_secure_link_seal(cipher, mac, s_key, s_nonce, s_ad, sizeof(s_ad), s_plain, sizeof(s_plain));
    TEST_ASSERT_EQUAL_UINT8_ARRAY(s_expected_cipher, cipher, sizeof(cipher));
    TEST_ASSERT_EQUAL_UINT8_ARRAY(s_expected_mac, mac, sizeof(mac));
}

static void test_known_vector_opens_back_to_plaintext(void) {
    uint8_t plain[sizeof(s_plain)];
    bool ok = cads_secure_link_open(
        plain, s_expected_mac, s_key, s_nonce, s_ad, sizeof(s_ad), s_expected_cipher,
        sizeof(s_expected_cipher));
    TEST_ASSERT_TRUE(ok);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(s_plain, plain, sizeof(plain));
}

static void test_round_trip_with_no_associated_data(void) {
    const uint8_t plain[] = "no ad this time";
    uint8_t cipher[sizeof(plain)];
    uint8_t mac[CADS_SECURE_LINK_MAC_LEN];
    cads_secure_link_seal(cipher, mac, s_key, s_nonce, NULL, 0u, plain, sizeof(plain));

    uint8_t opened[sizeof(plain)];
    bool ok = cads_secure_link_open(opened, mac, s_key, s_nonce, NULL, 0u, cipher, sizeof(cipher));
    TEST_ASSERT_TRUE(ok);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(plain, opened, sizeof(plain));
}

static void test_tampered_ciphertext_is_rejected(void) {
    uint8_t cipher[sizeof(s_expected_cipher)];
    memcpy(cipher, s_expected_cipher, sizeof(cipher));
    cipher[0] ^= 0x01u; /* flip one bit */

    uint8_t plain[sizeof(s_plain)];
    bool ok = cads_secure_link_open(
        plain, s_expected_mac, s_key, s_nonce, s_ad, sizeof(s_ad), cipher, sizeof(cipher));
    TEST_ASSERT_FALSE(ok);
}

static void test_tampered_mac_is_rejected(void) {
    uint8_t mac[CADS_SECURE_LINK_MAC_LEN];
    memcpy(mac, s_expected_mac, sizeof(mac));
    mac[0] ^= 0x01u;

    uint8_t plain[sizeof(s_plain)];
    bool ok = cads_secure_link_open(
        plain, mac, s_key, s_nonce, s_ad, sizeof(s_ad), s_expected_cipher, sizeof(s_expected_cipher));
    TEST_ASSERT_FALSE(ok);
}

static void test_wrong_key_is_rejected(void) {
    uint8_t wrong_key[CADS_SECURE_LINK_KEY_LEN];
    memcpy(wrong_key, s_key, sizeof(wrong_key));
    wrong_key[0] ^= 0x01u;

    uint8_t plain[sizeof(s_plain)];
    bool ok = cads_secure_link_open(
        plain, s_expected_mac, wrong_key, s_nonce, s_ad, sizeof(s_ad), s_expected_cipher,
        sizeof(s_expected_cipher));
    TEST_ASSERT_FALSE(ok);
}

static void test_wrong_associated_data_is_rejected(void) {
    static const uint8_t wrong_ad[12] = {
        0x43u, 0x61u, 0x44u, 0x53u, 0x20u, 0x5au, 0x65u, 0x72u, 0x6fu, 0x20u, 0x41u, 0x45u};

    uint8_t plain[sizeof(s_plain)];
    bool ok = cads_secure_link_open(
        plain, s_expected_mac, s_key, s_nonce, wrong_ad, sizeof(wrong_ad), s_expected_cipher,
        sizeof(s_expected_cipher));
    TEST_ASSERT_FALSE(ok);
}

/* The header's own contract: a caller must never be able to accidentally
 * trust stale sensitive data from a reused buffer after a failed open. */
static void test_failure_wipes_the_output_buffer(void) {
    uint8_t plain[sizeof(s_plain)];
    memset(plain, 0xAAu, sizeof(plain)); /* sentinel - would never legitimately appear */

    uint8_t bad_mac[CADS_SECURE_LINK_MAC_LEN];
    memcpy(bad_mac, s_expected_mac, sizeof(bad_mac));
    bad_mac[0] ^= 0x01u;

    bool ok = cads_secure_link_open(
        plain, bad_mac, s_key, s_nonce, s_ad, sizeof(s_ad), s_expected_cipher,
        sizeof(s_expected_cipher));
    TEST_ASSERT_FALSE(ok);

    uint8_t zeros[sizeof(s_plain)];
    memset(zeros, 0, sizeof(zeros));
    TEST_ASSERT_EQUAL_UINT8_ARRAY(zeros, plain, sizeof(plain));
}

static void test_seal_open_may_alias(void) {
    /* header documents in-place operation as supported (Monocypher's own
     * contract) - exercise it for real rather than only asserting the doc
     * comment reads that way. */
    uint8_t buffer[sizeof(s_plain)];
    memcpy(buffer, s_plain, sizeof(buffer));
    uint8_t mac[CADS_SECURE_LINK_MAC_LEN];

    cads_secure_link_seal(buffer, mac, s_key, s_nonce, s_ad, sizeof(s_ad), buffer, sizeof(buffer));
    TEST_ASSERT_EQUAL_UINT8_ARRAY(s_expected_cipher, buffer, sizeof(buffer));

    bool ok = cads_secure_link_open(buffer, mac, s_key, s_nonce, s_ad, sizeof(s_ad), buffer, sizeof(buffer));
    TEST_ASSERT_TRUE(ok);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(s_plain, buffer, sizeof(buffer));
}

int main(void) {
    UNITY_BEGIN();
    RUN_TEST(test_known_vector_matches_libsodium);
    RUN_TEST(test_known_vector_opens_back_to_plaintext);
    RUN_TEST(test_round_trip_with_no_associated_data);
    RUN_TEST(test_tampered_ciphertext_is_rejected);
    RUN_TEST(test_tampered_mac_is_rejected);
    RUN_TEST(test_wrong_key_is_rejected);
    RUN_TEST(test_wrong_associated_data_is_rejected);
    RUN_TEST(test_failure_wipes_the_output_buffer);
    RUN_TEST(test_seal_open_may_alias);
    return UNITY_END();
}
